import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/context/auth.context";
import ChatProvider from "@/context/chat.context";
import MessagesProvider from "@/context/messages.contex";
import SettingsProvider from "@/context/settings.context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <ChatProvider>
            <MessagesProvider>
              <SettingsProvider>{children}</SettingsProvider>
            </MessagesProvider>
          </ChatProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
